server:
  port: 8081

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/iguang-demo?useUnicode=yes&characterEncoding=UTF-8&useSSL=false
    username: root
    password: lgroot
  session:
    store-type: none